
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:${JELLYFIN_TAG_VERSION:-latest}
    container_name: jellyfin
    environment:
      - PUID=${UID:-568}
      - PGID=${GID:-568}
      - TZ=${TIMEZONE:-Etc/UTC}
      #- JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - ${DOCKER_VOLUME_STORAGE:?required-docker-root-volume-storage}/jellyfin/config:/config
      - ${DOCKER_MEDIA_STORAGE:?required-media-folder}:/mnt
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - internal
    labels:
      wud.display.name: Jellyfin
      wud.display.icon: si:jellyfin
      wud.watch.digest: true
      wud.tag.include: ^\d{1,3}\.\d+\.\d+$$

  jellyseerr:
    image: fallenbagel/jellyseerr:${JELLYSEERR_TAG_VERSION:-v2.1.0}
    container_name: jellyseerr
    user: ${UID:-568}:${GID:-568}
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE:-Etc/UTC}
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ${DOCKER_VOLUME_STORAGE:?required-docker-root-volume-storage}/jellyfin/jellyseer-config:/app/config
    restart: unless-stopped
    networks:
      - internal
      - arr_internal
    labels:
      wud.display.name: Jellyseerr
      wud.display.icon: mdi:jellyfish
      wud.watch.digest: true
      wud.tag.include: ^\d+\.\d+\.\d+$$

networks:
  internal:
  arr_internal:
    external: true
